# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-19 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/background', verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Background Image',
                'verbose_name_plural': 'Background images',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Category Title')),
                ('description', models.TextField(verbose_name='Category Description')),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your full name', max_length=400, verbose_name='Full Name')),
                ('number', models.CharField(help_text='Please enter your contact number', max_length=11, verbose_name='Contact Number')),
                ('email', models.CharField(help_text='Please enter your Email address', max_length=400, verbose_name='Email Address')),
                ('message', models.TextField(help_text='How can I help?', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email',
            },
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Facebook Links',
                'verbose_name_plural': 'FB Links',
            },
        ),
        migrations.CreateModel(
            name='HomeMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(upload_to=b'')),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Instagram Links',
                'verbose_name_plural': 'Insta Links',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image1', models.ImageField(upload_to='images/gallery', verbose_name='Image 1')),
                ('desc1', models.TextField(verbose_name='Image 1 Description')),
                ('image2', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 2')),
                ('desc2', models.TextField(blank=True, help_text='Only required if image 2 is uploaded', null=True, verbose_name='Image 2 Description')),
                ('image3', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 3 Description')),
                ('desc3', models.TextField(blank=True, help_text='Only required if image 3 is uploaded', null=True, verbose_name='Image 3 Description')),
                ('image4', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 4 Description')),
                ('desc4', models.TextField(blank=True, help_text='Only required if image 4 is uploaded', null=True, verbose_name='Image 4 Description')),
                ('image5', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 5 Description')),
                ('desc5', models.TextField(blank=True, help_text='Only required if image 5 is uploaded', null=True, verbose_name='Image 5 Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roberto_site.Category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
    ]
