# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Families',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/portraits')),
            ],
            options={
                'verbose_name': 'Families Image',
                'verbose_name_plural': 'Families Gallery',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/portraits')),
            ],
            options={
                'verbose_name': 'Food Image',
                'verbose_name_plural': 'Food Gallery',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/portraits')),
            ],
            options={
                'verbose_name': 'Music Image',
                'verbose_name_plural': 'Music Gallery',
            },
        ),
        migrations.CreateModel(
            name='Portraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/portraits')),
            ],
            options={
                'verbose_name': 'Portrait Image',
                'verbose_name_plural': 'Portrait Gallery',
            },
        ),
        migrations.CreateModel(
            name='Weddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/portraits')),
            ],
            options={
                'verbose_name': 'Wedding Image',
                'verbose_name_plural': 'Wedding Gallery',
            },
        ),
    ]
