# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email',
            },
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Facebook Links',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Instagram Links',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone',
            },
        ),
    ]
