# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0002_email_facebook_instagram_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(upload_to=b'')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
