# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0002_auto_20190405_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portraits',
            name='image1',
            field=models.ImageField(upload_to='images/portraits<django.db.models.fields.charfield>'),
        ),
    ]
