# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0003_auto_20190405_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portraits',
            name='image1',
            field=models.ImageField(upload_to='images/portraits'),
        ),
        migrations.AlterField(
            model_name='portraits',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/portraits'),
        ),
        migrations.AlterField(
            model_name='portraits',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/portraits'),
        ),
        migrations.AlterField(
            model_name='portraits',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/portraits'),
        ),
        migrations.AlterField(
            model_name='portraits',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/portraits'),
        ),
    ]
