# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0003_auto_20190405_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portraits',
            name='image1',
            field=models.ImageField(upload_to='images/portraits', verbose_name='Image 1'),
        ),
    ]
