# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0003_homemusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemusic',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
