# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0004_homemusic_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebook',
            options={'verbose_name': 'Facebook Links', 'verbose_name_plural': 'FB Links'},
        ),
        migrations.AlterModelOptions(
            name='instagram',
            options={'verbose_name': 'Instagram Links', 'verbose_name_plural': 'Insta Links'},
        ),
    ]
