# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0005_auto_20190413_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your full name', max_length=400, verbose_name='Full Name')),
                ('number', models.CharField(help_text='Please enter your contact number', max_length=11, verbose_name='Contact Nuber')),
                ('email', models.CharField(help_text='Please enter your Email address', max_length=400, verbose_name='Email address')),
                ('message', models.TextField(help_text='How can I help?', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
            },
        ),
    ]
