# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0005_auto_20190405_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 3 Description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image4',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 4 Description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image5',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 5 Description'),
        ),
    ]
