# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0007_auto_20190405_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Category Title')),
                ('description', models.TextField(verbose_name='Category Description')),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image1', models.ImageField(upload_to='images/gallery', verbose_name='Image 1')),
                ('desc1', models.TextField(verbose_name='Image 1 Description')),
                ('image2', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 2')),
                ('desc2', models.TextField(blank=True, help_text='Only required if image 2 is uploaded', null=True, verbose_name='Image 2 Description')),
                ('image3', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 3 Description')),
                ('desc3', models.TextField(blank=True, help_text='Only required if image 3 is uploaded', null=True, verbose_name='Image 3 Description')),
                ('image4', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 4 Description')),
                ('desc4', models.TextField(blank=True, help_text='Only required if image 4 is uploaded', null=True, verbose_name='Image 4 Description')),
                ('image5', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='images/gallery', verbose_name='Image 5 Description')),
                ('desc5', models.TextField(blank=True, help_text='Only required if image 5 is uploaded', null=True, verbose_name='Image 5 Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='roberto_site.Category')),
            ],
            options={
                'verbose_name': 'Portrait Image',
                'verbose_name_plural': 'Portrait Gallery',
            },
        ),
        migrations.DeleteModel(
            name='Portraits',
        ),
    ]
