# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0008_auto_20190413_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
    ]
