# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roberto_site', '0009_auto_20190413_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Families',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Weddings',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roberto_site.Category'),
        ),
    ]
